"""empty message

Revision ID: 4c073dc90815
Revises: None
Create Date: 2016-06-06 18:56:27.305482

"""

# revision identifiers, used by Alembic.
revision = '4c073dc90815'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('station',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recording',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['station'], ['station.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recording')
    op.drop_table('station')
    ### end Alembic commands ###
